#!/bin/sh

cd /ha-conf/
if [ ! -d "/ha-conf/.git" ]; then
   while ! ping -c1 github.com &>/dev/null; do echo "host not responding"; done
   echo "Starting automatic setup for HA"
   git init --initial-branch=main
   echo "Adding remote"
   git remote add origin git@github.com:Gerry546/Reterminal-Homeassistant.git
   git clean -d -f .
   git pull origin main -f
   echo "Getting submodules"
   git submodule update --init
else
   echo "Found existing .git directory. skipping...."
   exit 0
fi
