#!/bin/sh

cd /ha-conf/
if [ -z "$(ls -A /ha-conf/.git)" ]; then
   echo "Starting automatic setup for HA"
   git init --initial-branch=main
   echo "Adding remote"
   git remote add origin git@github.com:Estalor/Reterminal-Homeassistant.git
   git clean -d -f .
   git pull origin main -f
   echo "Getting submodules"
   git submodule update --init
else
   echo "Directory not empty. skipping...."
   exit 0
fi
